### ISSUE TITLE
where are the files stored?

### ISSUE THREAD

**Issue by Merith-TK** [draguve/droidducky-app#14]
I want to write some DuckyScripts on my PC then transfer them to my phone. where are the files stored?

**Comment by draguve** [comment]
Its not currently possible , but i am working on it , Im changing the entire way the scripts are stored to make it a bit easier

**Comment by Merith-TK** [comment]
Yeah I looked around the filesystem and found a sqlite database that had
the information...

If I knew more about app development I would gladly help!

**Comment by draguve** [comment]
Ya that sqldatabase was a bad idea from the get go

**Comment by Merith-TK** [comment]
Well...

If it were to be reworked, how I would do it is look for files in 
`$INTERNAL_STORAGE/Documents/DroidDucky/scripts`

**Comment by draguve** [comment]
i reworked it , you can now just copy paste the duckyscripts in 
`$INTERNAL_STORAGE/Droidducky/DuckyScripts`

and js scripts in 
`$INTERNAL_STORAGE/Droidducky/JavaScript`
