### ISSUE TITLE
Files are not saved?

### ISSUE THREAD

**Issue by Merith-TK** [draguve/droidducky-app#16]
https://hastebin.com/manusotoyu.sql
(retreived from debugger in Android Studio)

all i am making is a script that does `GUI r`

it looks like the app tries to write to `/storage/emulated/0/Droidducky/DuckyScripts/Sun,16-Jun-2019-17:02:45.txt` but the directories `/storage/emulated/0/Droidducky` and `/storage/emulated/0/Droidducky/DuckyScripts/`

do not exist in my android phone, might wanna have it make the folders if they don't exist

A reply to this will be made with successful output

**Comment by Merith-TK** [comment]
(Forgot to delete app first)~~https://hastebin.com/okekunuhik.sql~~
https://hastebin.com/xiquqetequ.sql < new debug link
Successful save after manually making the directories that were missing

**Comment by draguve** [comment]
im sorry the links are empty for me , but it should make the folders by itself

**Comment by Merith-TK** [comment]
It doesnt. It makes a error that the file/folder does not exist. (the Linux
error when you try to touch a file when the. Folders don't exist)

/sdcard/ducky/duckt.txt: No such file or directory

This was made with Termux, but the error is exactly the same

**Comment by draguve** [comment]
sorry for the time delay , got really busy with life , fixed it , was a stupid error
