### ISSUE TITLE
LOCAL_IP

### ISSUE THREAD

**Issue by thehappydinoa** [draguve/droidducky-app#9]
Hey,

I think `LOCAL_IP` is statically set to `192.168.42.129`.

This is beyond me.

**Comment by draguve** [comment]
Ya If I remember correctly it is statically set to 192.168.42.129 for ASOP Android but some roms implement a ui to change the usb tethering ip as well as the hotspot ip's

**Comment by thehappydinoa** [comment]
Ah ok, maybe I can find a way to get the usb tethering ip.
